name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: 17 2 * * *
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: $
